SELECT 
CODIGOORDEN
,PROPIETARIO
,SUM(CANTIDADESPERADA) AS CANTIDADESPERADA
,SUM(CANTIDADRECIBIDA) AS CANTIDADRECIBIDA
,(CASE WHEN CANTIDADRECIBIDA = 0 OR  CANTIDADESPERADA= 0 THEN 0 
ELSE (CANTIDADRECIBIDA)/(CANTIDADESPERADA) END) AS FILLRATE
,PROVEEDOR
,ST.DESCRIPTION AS NOMBREPROVEEDOR
,FECHARECEPCION
FROM(SELECT
RD.RECEIPTKEY AS CODIGOORDEN,
MAX(RD.STORERKEY) AS PROPIETARIO,
MAX(RD.SKU) AS ARTICULO,
SUM(RD.QTYEXPECTED) AS CANTIDADESPERADA,
SUM(RD.QTYRECEIVED) AS CANTIDADRECIBIDA,
PA.CASECNT AS FACTOR,
MAX(RC.SUPPLIERCODE) AS PROVEEDOR,
CAST(MAX(RD.DATERECEIVED) AS DATE) AS FECHARECEPCION
FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.PACK AS PA
ON RD.PACKKEY = PA.PACKKEY
LEFT JOIN WMWHSE51.RECEIPT AS RC
ON RD.RECEIPTKEY = RC.RECEIPTKEY
--WHERE RD.STORERKEY like '1770142'
GROUP BY RD.RECEIPTKEY, PA.CASECNT, RD.QTYEXPECTED, RD.QTYRECEIVED
)T0 
LEFT JOIN WMWHSE51.STORER AS ST
ON T0.PROVEEDOR = ST.STORERKEY
GROUP BY CODIGOORDEN, PROPIETARIO, PROVEEDOR, FECHARECEPCION,CANTIDADRECIBIDA, CANTIDADESPERADA, ST.DESCRIPTION 