SELECT
RD.RECEIPTKEY AS CODIGOASN,
RD.REFERENCEDOCUMENT AS CODIGOORDEN,
RD.SKU AS CODIGO,
SK.DESCR AS DESCRIPCION,
(RD.QTYRECEIVED/PA.CASECNT) AS CANTIDADRECIBIDA,
RD.LOTTABLE05 AS FECHAVENCIMIENTO,
RD.SUPPLIERKEY AS PROVEEDOR,
CAST(RD.DATERECEIVED AS DATE) AS FECHA,
CAST(RD.DATERECEIVED AS TIME) AS HORA,
RD.TOID AS ETIQUETA,
RD.STORERKEY AS PROPIETARIO,
RD.ADDWHO USUARIO
FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.SKU AS SK
ON RD.SKU = SK.SKU AND RD.STORERKEY = SK.STORERKEY
LEFT JOIN WMWHSE51.PACK AS PA
ON RD.PACKKEY = PA.PACKKEY
WHERE RD.QTYRECEIVED > 0