SELECT
RD.RECEIPTKEY AS CODIGOASN
,RD.REFERENCEDOCUMENT AS CODIGOORDEN
,RD.SKU AS CODIGO
,SK.DESCR AS DESCRIPCION
,PA.CASECNT AS FACTOR
,RD.QTYRECEIVED AS UNIDADES
,RD.QTYRECEIVED/PA.CASECNT AS CAJAS
,CAST(RD.DATERECEIVED AS DATE) AS FECHARECEPCION
,RD.TOID AS ETIQUETA
,RD.STORERKEY AS PROPIETARIO
FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.SKU AS SK
ON RD.SKU = SK.SKU AND RD.STORERKEY = SK.STORERKEY
LEFT JOIN WMWHSE51.PACK AS PA
ON RD.PACKKEY = PA.PACKKEY
WHERE RD.TOID <> '' AND RD.STORERKEY LIKE '1770142'