SELECT
MAX(CODIGOASN) AS CODIGOASN
,MAX(CODIGOORDEN) AS CODIGOORDEN
,MAX(CODPROVEEDOR) AS CODPROVEEDOR
,MAX(ST.DESCRIPTION) AS PROVEEDOR
,CODIGO
,MAX(EAN13) AS EAN13
,MAX(DUN14) AS DUN14
,MAX(DESCRIPCION) AS DESCRIPCION
,MAX(DIASCADUCIDAD) AS DIASCADUCIDAD
,MAX(DIASPRECADUCIDAD) AS DIASPRECADUCIDAD
,MAX(UNIDADESCAJA) AS UNIDADESCAJA
,MAX(CAJASLAYER) AS CAJASLAYER
,MAX(LAYERPALLET) AS LAYERPALLET
--,UNIDADESPACK
,sum(CAJAS)/MAX(UNIDADESCAJA) as CAJAS
--,PACKS
,MAX(VENCE) AS VENCE
,MAX(CADUCIDAD) AS CADUCIDAD
--,MAQUILA
FROM(
SELECT
RD.RECEIPTKEY AS CODIGOASN,
RD.SUPPLIERKEY AS CODPROVEEDOR,
RD.SKU AS CODIGO,
AL1.ALTSKU AS EAN13,
AL.ALTSKU AS DUN14,
SK.DESCR AS DESCRIPCION,
SK.SHELFLIFE AS DIASCADUCIDAD,
SK.SHELFLIFEONRECEIVING AS DIASPRECADUCIDAD,
PA.CASECNT AS UNIDADESCAJA,
PA.PALLETTI AS CAJASLAYER,
PA.PALLETHI AS LAYERPALLET,
(RD.QTYRECEIVED) AS CAJAS,
RD.LOTTABLE05 AS VENCE,
DATEADD(DAY,-SK.SHELFLIFE,RD.DATERECEIVED) AS CADUCIDAD,
RD.REFERENCEDOCUMENT AS CODIGOORDEN
FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.ALTSKU AS AL
ON RD.SKU = AL.SKU AND RD.STORERKEY = AL.STORERKEY
LEFT JOIN WMWHSE51.ALTSKU AS AL1
ON RD.SKU = AL1.SKU AND RD.STORERKEY = AL1.STORERKEY
LEFT JOIN WMWHSE51.SKU AS SK
ON RD.SKU = SK.SKU
LEFT JOIN WMWHSE51.PACK AS PA
ON RD.PACKKEY = PA.PACKKEY
)T1 
LEFT JOIN WMWHSE51.STORER AS ST
ON T1.CODPROVEEDOR = ST.STORERKEY
GROUP BY CODIGO
