SELECT 
UNIDADESCAJA
,CAJASLAYER
,LAYERPALLET
,CODIGO
,DESCRIPCION
,FECHA
,PROVEEDOR
,CODIGOORDEN
,(CASE when CANTIDADESPERADA = 0 or PALLETS = 0 THEN 0
ELSE CANTIDADESPERADA/PALLETS END)PALLETS
,(CASE WHEN CANTIDADESPERADA = 0 OR BULTOS = 0 THEN 0
ELSE CANTIDADESPERADA/BULTOS END) BULTOS
FROM(SELECT PA.CASECNT AS UNIDADESCAJA,
       PA.PALLETTI AS CAJASLAYER,
       PA.PALLETHI AS LAYERPALLET,
       RD.SKU AS CODIGO,
       SK.DESCR AS DESCRIPCION,
       RC.RECEIPTDATE AS FECHA,
       RD.SUPPLIERNAME AS PROVEEDOR,
       RD.RECEIPTKEY AS CODIGOORDEN,
       RD.QTYEXPECTED AS CANTIDADESPERADA,
       PA.PALLET AS PALLETS,
       PA.CASECNT AS BULTOS
FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.PACK AS PA ON RD.PACKKEY = PA.PACKKEY
INNER JOIN WMWHSE51.RECEIPT AS RC ON RD.RECEIPTKEY = RC.RECEIPTKEY
LEFT JOIN WMWHSE51.SKU AS SK ON RD.SKU = SK.SKU
AND RD.STORERKEY = SK.STORERKEY
WHERE RD.QTYEXPECTED > 0)T0