SELECT
ORDENCOMPRA
,CODIGOASN
,CAST(FECHA AS DATE) AS FECHA
,CODIGOARTICULO
,DESCRIPCION
,TOTAL
,FACTOREMPAQUE
,(CASE WHEN TOTAL = 0 OR FACTOREMPAQUE = 0 THEN 0
ELSE TOTAL/FACTOREMPAQUE END
)AS CAJAS
FROM(SELECT
RD.REFERENCEDOCUMENT AS ORDENCOMPRA,
RD.RECEIPTKEY AS CODIGOASN,
MAX(RD.ADDDATE) AS FECHA,
MAX(RD.SKU) AS CODIGOARTICULO,
MAX(SK.DESCR) AS DESCRIPCION,
SUM(RD.QTYRECEIVED) AS TOTAL,
MAX(PA.CASECNT) AS FACTOREMPAQUE
FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.SKU AS SK
ON RD.SKU = SK.SKU AND RD.STORERKEY = RD.STORERKEY
LEFT JOIN WMWHSE51.PACK AS PA
ON RD.PACKKEY = RD.PACKKEY
GROUP BY RD.REFERENCEDOCUMENT, RD.RECEIPTKEY)t0