SELECT

FROM(
SELECT
1 as Cant,
MAX(RD.RECEIPTKEY) AS CODIGOORDEN,
MAX(RD.SUPPLIERKEY) AS PROVEEDOR,
RD.SKU AS CODIGO,
MAX(AL.ALTSKU) AS EAN13,
MAX(SK.DESCR) AS DESCRIPCION,
MAX(PA.CASECNT) AS FACTOR,
SUM(RD.QTYEXPECTED) AS UNIDADESPEDIDAS,
SUM((RD.QTYEXPECTED/PA.CASECNT)) AS CAJASPEDIDAS,
SUM(RD.QTYRECEIVED) AS UNIDADESRECIBIDAS,
SUM((RD.QTYRECEIVED/PA.CASECNT)) AS CAJASRECIBIDAS,
SUM((RD.QTYRECEIVED-RD.QTYEXPECTED)) AS DIFERENCIAUNIDADES,
SUM(((RD.QTYRECEIVED-RD.QTYEXPECTED)/PA.CASECNT)) AS DIFERENCIACAJAS,
SUM((RD.QTYEXPECTED/PA.PALLET)) AS PALLETESPERADO,
SUM((RD.QTYRECEIVED/PA.PALLET)) AS PALLETRECIBIDO
FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.SKU AS SK
ON RD.SKU = SK.SKU AND RD.STORERKEY = SK.STORERKEY
LEFT JOIN WMWHSE51.ALTSKU AS AL
ON RD.SKU = AL.SKU AND AL.TYPE LIKE 'EAN13'
LEFT JOIN WMWHSE51.PACK AS PA
ON RD.PACKKEY = PA.PACKKEY
--WHERE RD.RECEIPTKEY LIKE '0000000321'
GROUP BY RD.SKU
)