--ETUQUETAS POR USUARIO--
SELECT 
UA.ITRNKEY AS IDTAREA,
UA.ACTYPE AS TIPO,
IT.FROMID AS ETIQUETAORIGEN,--1
IT.TOID AS ETIQUETADESTINO,--2
UA.TYPE ,
(CASE UA.TYPE WHEN  'PA' THEN 'ALMACENAJE'
WHEN 'RP' THEN 'REABASTECIMIENTO'
WHEN 'RC' THEN 'RECEPCION'
WHEN 'ASSTPK' THEN 'PICKING ASISTIDO'
WHEN 'ASSTMV' THEN 'EXTRACCION ASISTIDO'
WHEN 'PK' THEN 'PICKING'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO'
WHEN 'MV' THEN 'EXTRACCION'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO' 
ELSE 'TIPO '+UA.TYPE+' NO TRADUCIDO'END) AS TIPOOPERACION,--3
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) AS FECHA,--4
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, UA.ADDDATE), 111))AS HORA,--5
UA.USERID AS USUARIO,--6
UA.EQUIPMENTID AS EQUIPO,--7
IT.FROMLOC AS UBICACIONRIGEN,--8
IT.TOLOC AS UBICACIONDESTINO,--9
IT.SKU as ARTICULO,--10
S.DESCR AS DESCRIPCION,--11
(CASE WHEN P.CASECNT IS NULL OR P.CASECNT = 0 THEN 0 ELSE IT.QTY/P.CASECNT END) AS CANTIDADCAJAS,--12
IT.QTY AS CANTIDADUNIDADES,
UA.STARTTIME AS INICIO,--13
UA.ENDTIME AS FIN--14
FROM WMWHSE51.USERACTIVITY AS UA
INNER JOIN WMWHSE51.ITRN AS IT
ON UA.ITRNKEY = IT.ITRNKEY
INNER JOIN WMWHSE51.SKU AS S
ON IT.SKU = S.SKU AND IT.storerkey = S.storerkey
INNER JOIN WMWHSE51.PACK AS P
ON IT.PACKKEY = P.PACKKEY

----INDICEPRODUCCIONXETIQUETAS---
SELECT 
COUNT(USERACTIVITYKEY) AS MOVIMIENTOS,
TIPOOPERACION,
FECHA,
HORA,
USUARIO,
EQUIPO,
SUM(CANTIDADCAJAS) AS CANTIDADCAJAS, 
SUM(CANTIDADUNIDADES) AS CANTIDADUNIDADES
FROM(
SELECT 
UA.TYPE ,
IT.FROMID AS ETIQUETAORIGEN,
IT.TOID AS ETIQUETADESTINO,
UA.USERACTIVITYKEY,
(CASE UA.TYPE WHEN  'PA' THEN 'ALMACENAJE'
WHEN 'RP' THEN 'REABASTECIMIENTO'
WHEN 'RC' THEN 'RECEPCION'
WHEN 'ASSTPK' THEN 'PICKING ASISTIDO'
WHEN 'ASSTMV' THEN 'EXTRACCION ASISTIDO'
WHEN 'PK' THEN 'PICKING'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO'
WHEN 'MV' THEN 'EXTRACCION'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO' 
ELSE 'TIPO '+UA.TYPE+' NO TRADUCIDO'END) AS TIPOOPERACION,
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) AS FECHA,
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, UA.ADDDATE), 111))AS HORA,
UA.USERID AS USUARIO,
UA.EQUIPMENTID AS EQUIPO,
(IT.QTY/P.CASECNT)AS CANTIDADCAJAS,
IT.QTY AS CANTIDADUNIDADES
FROM WMWHSE51.ITRN AS IT
INNER JOIN WMWHSE51.USERACTIVITY AS UA
ON UA.ITRNKEY = IT.ITRNKEY
INNER JOIN WMWHSE51.SKU AS S
ON S.SKU = IT.SKU AND S.storerkey = IT.storerkey
INNER JOIN WMWHSE51.PACK AS P
ON IT.PACKKEY = P.PACKKEY
WHERE DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, UA.ADDDATE), 111)) = 10 AND CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) = '2024-02-20' AND UA.TYPE LIKE 'PA'
)T0
GROUP BY TIPOOPERACION, FECHA, HORA, USUARIO, EQUIPO

--- esto es fin--

SELECT
UA.ITRNKEY AS IDTAREA,
UA.ACTYPE AS TIPO,
IT.FROMID AS ETIQUETAORIGEN,--1
IT.TOID AS ETIQUETADESTINO,--2
UA.TYPE ,
(CASE UA.TYPE WHEN  'PA' THEN 'ALMACENAJE'
WHEN 'RP' THEN 'REABASTECIMIENTO'
WHEN 'RC' THEN 'RECEPCION'
WHEN 'ASSTPK' THEN 'PICKING ASISTIDO'
WHEN 'ASSTMV' THEN 'EXTRACCION ASISTIDO'
WHEN 'PK' THEN 'PICKING'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO'
WHEN 'MV' THEN 'EXTRACCION'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO'
ELSE 'TIPO '+UA.TYPE+' NO TRADUCIDO'END) AS TIPOOPERACION,--3
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) AS FECHA,--4
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, UA.ADDDATE), 111))AS HORA,--5
UA.USERID AS USUARIO,--6
UA.EQUIPMENTID AS EQUIPO,--7
IT.FROMLOC AS UBICACIONRIGEN,--8
IT.TOLOC AS UBICACIONDESTINO,--9
IT.SKU as ARTICULO,--10
S.DESCR AS DESCRIPCION,--11
(CASE WHEN P.CASECNT IS NULL OR P.CASECNT = 0 THEN 0 ELSE IT.QTY/P.CASECNT END) AS CANTIDADCAJAS,--12
IT.QTY AS CANTIDADUNIDADES,
UA.STARTTIME AS INICIO,--13
UA.ENDTIME AS FIN--14
FROM WMWHSE51.USERACTIVITY AS UA
INNER JOIN WMWHSE51.ITRN AS IT
ON UA.ITRNKEY = IT.ITRNKEY
INNER JOIN WMWHSE51.SKU AS S
ON IT.SKU = S.SKU AND IT.storerkey = S.storerkey
INNER JOIN WMWHSE51.PACK AS P
ON IT.PACKKEY = P.PACKKEY
UNION ALL
SELECT
UA.ITRNKEY AS IDTAREA,
UA.ACTYPE AS TIPO,
PD.DROPID AS ETIQUETAORIGEN,--1
PD.ID AS ETIQUETADESTINO,--2
UA.TYPE ,
(CASE UA.TYPE WHEN  'PA' THEN 'ALMACENAJE'
WHEN 'RP' THEN 'REABASTECIMIENTO'
WHEN 'RC' THEN 'RECEPCION'
WHEN 'ASSTPK' THEN 'PICKING ASISTIDO'
WHEN 'ASSTMV' THEN 'EXTRACCION ASISTIDO'
WHEN 'PK' THEN 'PICKING'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO'
WHEN 'MV' THEN 'EXTRACCION'
WHEN 'ASSTPA' THEN 'ALMACENAJE ASISTIDO'
ELSE 'TIPO '+UA.TYPE+' NO TRADUCIDO'END) AS TIPOOPERACION,--3
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) AS FECHA,--4
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, UA.ADDDATE), 111))AS HORA,--5
UA.USERID AS USUARIO,--6
UA.EQUIPMENTID AS EQUIPO,--7
PD.FROMLOC AS UBICACIONRIGEN,--8
PD.TOLOC AS UBICACIONDESTINO,--9
PD.SKU as ARTICULO,--10
S.DESCR AS DESCRIPCION,--11
(CASE WHEN P.CASECNT IS NULL OR P.CASECNT = 0 THEN 0 ELSE PD.QTY/P.CASECNT END) AS CANTIDADCAJAS,--12
PD.QTY AS CANTIDADUNIDADES,
UA.STARTTIME AS INICIO,--13
UA.ENDTIME AS FIN--14
FROM WMWHSE51.USERACTIVITY AS UA
INNER JOIN WMWHSE51.PICKDETAIL AS PD
ON UA.PICKDETAILKEY = PD.PICKDETAILKEY
INNER JOIN WMWHSE51.SKU AS S
ON PD.SKU = S.SKU AND PD.storerkey = S.storerkey
INNER JOIN WMWHSE51.PACK AS P
ON PD.PACKKEY = P.PACKKEY


select * from WMWHSE51.USERACTIVITY
where type in('PK','ASSTPK')





-----

select 
ETIQUETAORIGEN
,ETIQUETADESTINO
,FECHA
,HORA
,USUARIO
,EQUIPO
,UBICACIONRIGEN
,UBICACIONDESTINO
,NIVELORIGEN
,NIVELDESTINO
,(CASE 
when NIVELORIGEN= 0 AND  NIVELDESTINO> 1 then 'Almacenaje'
when NIVELORIGEN= 0 AND  NIVELDESTINO= 1 then 'Reposicion desde canal'
when NIVELORIGEN> 1 AND  NIVELDESTINO= 1 then 'Reposicion'
when NIVELORIGEN> 1 AND  NIVELDESTINO= 0 then 'Extraccion'
when NIVELORIGEN= 1 AND  NIVELDESTINO= 0 then 'Picking'
when NIVELORIGEN= 0 AND  NIVELDESTINO= 0 then 'Recepcion'
else 'Operacion no mapeada..' end
) as OPERACION
,ARTICULO
,DESCRIPCION
,CANTIDADCAJAS
,CANTIDADUNIDADES
from(
SELECT 
TD.FROMID AS ETIQUETAORIGEN,
TD.TOID AS ETIQUETADESTINO,
CAST(DATEADD(HOUR,-6,TD.ADDDATE) AS DATE) AS FECHA,
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, TD.ADDDATE), 111))AS HORA,
TD.ADDWHO AS USUARIO,
TD.EQUIPMENTID AS EQUIPO,
cast(LO.LOCLEVEL as VARCHAR) AS NIVELORIGEN,
cast(LD.LOCLEVEL as VARCHAR) AS NIVELDESTINO,
CAST(TD.FROMLOC AS VARCHAR) AS UBICACIONRIGEN,
CAST(TD.TOLOC AS VARCHAR) AS UBICACIONDESTINO,
TD.SKU as ARTICULO,
S.DESCR AS DESCRIPCION,
(TD.QTY/PA.CASECNT) AS CANTIDADCAJAS,
TD.QTY AS CANTIDADUNIDADES
from WMWHSE51.TASKDETAIL AS TD
INNER JOIN WMWHSE51.SKU AS S
ON TD.SKU = S.SKU AND TD.STORERKEY = S.STORERKEY
INNER JOIN WMWHSE51.PACK AS PA
ON S.PACKKEY = PA.PACKKEY 
INNER JOIN WMWHSE51.LOC AS LO
ON LO.LOC = TD.FROMLOC
INNER JOIN WMWHSE51.LOC AS LD
ON LD.LOC = TD.TOLOC
)t1
union ALL
select 
ETIQUETAORIGEN
,ETIQUETADESTINO
,FECHA
,HORA
,USUARIO
,EQUIPO
,UBICACIONRIGEN
,UBICACIONDESTINO
,NIVELORIGEN
,NIVELDESTINO
,(CASE 
when NIVELORIGEN= 0 AND  NIVELDESTINO> 1 then 'Almacenaje'
when NIVELORIGEN= 0 AND  NIVELDESTINO= 1 then 'Reposicion desde canal'
when NIVELORIGEN> 1 AND  NIVELDESTINO= 1 then 'Reposicion'
when NIVELORIGEN> 1 AND  NIVELDESTINO= 0 then 'Extraccion'
when NIVELORIGEN= 1 AND  NIVELDESTINO= 0 then 'Picking'
when NIVELORIGEN= 0 AND  NIVELDESTINO= 0 then 'Recepcion'
else 'Operacion no mapeada.' end
) as OPERACION
,ARTICULO
,DESCRIPCION
,CANTIDADCAJAS
,CANTIDADUNIDADES
from(
SELECT
IT.FROMID AS ETIQUETAORIGEN,
IT.TOID AS ETIQUETADESTINO,
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) AS FECHA,
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, UA.ADDDATE), 111))AS HORA,
UA.USERID AS USUARIO,
UA.EQUIPMENTID AS EQUIPO,
CAST(IT.FROMLOC AS VARCHAR) AS UBICACIONRIGEN,
CAST(IT.TOLOC AS VARCHAR) AS UBICACIONDESTINO,
cast(isnull(LO.LOCLEVEL,0) as VARCHAR) AS NIVELORIGEN,
cast(isnull(LD.LOCLEVEL,0) as VARCHAR) AS NIVELDESTINO,
IT.SKU as ARTICULO,
S.DESCR AS DESCRIPCION,
(CASE WHEN P.CASECNT IS NULL OR P.CASECNT = 0 THEN 0 ELSE IT.QTY/P.CASECNT END) AS CANTIDADCAJAS,
IT.QTY AS CANTIDADUNIDADES
FROM WMWHSE51.USERACTIVITY AS UA
INNER JOIN WMWHSE51.ITRN AS IT
ON UA.ITRNKEY = IT.ITRNKEY
INNER JOIN WMWHSE51.SKU AS S
ON IT.SKU = S.SKU AND IT.storerkey = S.storerkey
INNER JOIN WMWHSE51.PACK AS P
ON IT.PACKKEY = P.PACKKEY
LEFT JOIN WMWHSE51.LOC AS LO
ON LO.LOC = IT.FROMLOC
LEFT JOIN WMWHSE51.LOC AS LD
ON LD.LOC = IT.TOLOC
where UA.TYPE IN ('RC')
)t0 WHERE 




---final---
select 
ETIQUETAORIGEN
,ETIQUETADESTINO
,FECHA
,HORA
,USUARIO
,EQUIPO
,UBICACIONRIGEN
,UBICACIONDESTINO
,TIPOUBICACIONORIGEN
,TIPOUBICACIONDESTINO
,(CASE 
when TIPOUBICACIONORIGEN = 'SORTLOC' AND  TIPOUBICACIONDESTINO = 'SORTLOC' then 'Recepcion'
when TIPOUBICACIONORIGEN = 'SORTLOC' AND  TIPOUBICACIONDESTINO = 'OTHER' then 'Almacenaje'
when TIPOUBICACIONORIGEN = 'SORTLOC' AND  TIPOUBICACIONDESTINO = 'CASE' then 'Reabastecimiento desde canal'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'CASE' then 'Reabastecimiento'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'PICKTO' then 'Extraccion'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'STAGED' then 'Extraccion'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'PICKTO' then 'Picking'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'STAGED' then 'Picking'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'OTHER' then 'Traslado'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'OTHER' then 'Traslado'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'SORTLOC' then 'Traslado'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'SORTLOC' then 'Traslado'
else 'Operacion no mapeada..' end
) as OPERACION
,ARTICULO
,DESCRIPCION
,CANTIDADCAJAS
,CANTIDADUNIDADES
from(
SELECT 
TD.FROMID AS ETIQUETAORIGEN,
TD.TOID AS ETIQUETADESTINO,
CAST(DATEADD(HOUR,-6,TD.ADDDATE) AS DATE) AS FECHA,
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, TD.ADDDATE), 111))AS HORA,
TD.ADDWHO AS USUARIO,
TD.EQUIPMENTID AS EQUIPO,
LO.LOCATIONTYPE AS TIPOUBICACIONORIGEN,
LD.LOCATIONTYPE AS TIPOUBICACIONDESTINO,
CAST(TD.FROMLOC AS VARCHAR) AS UBICACIONRIGEN,
CAST(TD.TOLOC AS VARCHAR) AS UBICACIONDESTINO,
TD.SKU as ARTICULO,
S.DESCR AS DESCRIPCION,
(CASE WHEN TD.UOM = 2 OR TD.UOM = 1 THEN (TD.QTY/PA.CASECNT) ELSE 0 END) AS CANTIDADCAJAS,
(CASE WHEN TD.UOM = 6 THEN TD.QTY ELSE 0 END) AS CANTIDADUNIDADES
from WMWHSE51.TASKDETAIL AS TD
INNER JOIN WMWHSE51.SKU AS S
ON TD.SKU = S.SKU AND TD.STORERKEY = S.STORERKEY
INNER JOIN WMWHSE51.PACK AS PA
ON S.PACKKEY = PA.PACKKEY 
INNER JOIN WMWHSE51.LOC AS LO
ON LO.LOC = TD.FROMLOC
INNER JOIN WMWHSE51.LOC AS LD
ON LD.LOC = TD.TOLOC
WHERE CAST(TD.ADDDATE AS DATE) BETWEEN  CAST(DATEADD(month,-3,TD.ADDDATE) AS DATE) AND  CAST(DATEADD(HOUR,-6,GETDATE()) AS DATE)
AND TD.STATUS LIKE '9'
)t1
union ALL
select 
ETIQUETAORIGEN
,ETIQUETADESTINO
,FECHA
,HORA
,USUARIO
,EQUIPO
,UBICACIONRIGEN
,UBICACIONDESTINO
,TIPOUBICACIONORIGEN
,TIPOUBICACIONDESTINO
,(CASE 
when TIPOUBICACIONORIGEN = 'SORTLOC' AND  TIPOUBICACIONDESTINO = 'SORTLOC' then 'Recepcion'
when TIPOUBICACIONORIGEN = 'SORTLOC' AND  TIPOUBICACIONDESTINO = 'OTHER' then 'Almacenaje'
when TIPOUBICACIONORIGEN = 'SORTLOC' AND  TIPOUBICACIONDESTINO = 'CASE' then 'Reabastecimiento desde canal'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'CASE' then 'Reabastecimiento'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'PICKTO' then 'Extraccion'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'STAGED' then 'Extraccion'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'PICKTO' then 'Picking'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'STAGED' then 'Picking'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'OTHER' then 'Traslado'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'OTHER' then 'Traslado'
when TIPOUBICACIONORIGEN = 'OTHER' AND  TIPOUBICACIONDESTINO = 'SORTLOC' then 'Traslado'
when TIPOUBICACIONORIGEN = 'CASE' AND  TIPOUBICACIONDESTINO = 'SORTLOC' then 'Traslado'
else 'Operacion no mapeada..' end
) as OPERACION
,ARTICULO
,DESCRIPCION
,CANTIDADCAJAS
,CANTIDADUNIDADES
from(
SELECT
IT.FROMID AS ETIQUETAORIGEN,
IT.TOID AS ETIQUETADESTINO,
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) AS FECHA,
DATEPART(HOUR, CONVERT(DATETIME,DATEADD(hour, -6, UA.ADDDATE), 111))AS HORA,
UA.USERID AS USUARIO,
UA.EQUIPMENTID AS EQUIPO,
isnull(IT.FROMLOC,'STAGE') AS UBICACIONRIGEN,
IT.TOLOC AS UBICACIONDESTINO,
isnull(LO.LOCATIONTYPE, 'SORTLOC') AS TIPOUBICACIONORIGEN,
LD.LOCATIONTYPE AS TIPOUBICACIONDESTINO,
IT.SKU as ARTICULO,
S.DESCR AS DESCRIPCION,
(CASE WHEN IT.UOM = 'CJ' OR IT.UOM = 'PL' THEN
(CASE WHEN P.CASECNT IS NULL OR P.CASECNT = 0 THEN 0 ELSE IT.QTY/P.CASECNT END) ELSE 0 END)
AS CANTIDADCAJAS,
(CASE WHEN IT.UOM = 'UN' THEN
IT.QTY ELSE 0 END)
AS CANTIDADUNIDADES 
FROM WMWHSE51.USERACTIVITY AS UA
INNER JOIN WMWHSE51.ITRN AS IT
ON UA.ITRNKEY = IT.ITRNKEY
INNER JOIN WMWHSE51.SKU AS S
ON IT.SKU = S.SKU AND IT.storerkey = S.storerkey
INNER JOIN WMWHSE51.PACK AS P
ON IT.PACKKEY = P.PACKKEY
LEFT JOIN WMWHSE51.LOC AS LO
ON LO.LOC = IT.FROMLOC
LEFT JOIN WMWHSE51.LOC AS LD
ON LD.LOC = IT.TOLOC
where UA.TYPE IN ('RC')
AND CAST(UA.ADDDATE AS DATE) BETWEEN  CAST(DATEADD(month,-3,UA.ADDDATE) AS DATE) AND  CAST(DATEADD(HOUR,-6,GETDATE()) AS DATE)
)t0