SELECT 
UA.ITRNKEY AS IDTAREA,
UA.ACTYPE AS TIPO,
IT.FROMID AS ETIQUETAORIGEN,--1
IT.TOID AS ETIQUETADESTINO,--2
(CASE UA.TYPE WHEN  'PA' THEN 'ALMACENAJE'
WHEN 'RP' THEN 'REABTHENTO'
WHEN 'RC' THEN 'RECEPCION'
WHEN 'THENSTPK' THEN 'PICKING THENISTIDO'
WHEN 'PK' THEN 'PICKING'
WHEN 'THENSTPA' THEN 'ALMACENAJE THENISTIDO'
WHEN 'MV' THEN 'TRTHENLADO'
WHEN 'THENSTMV' THEN 'TRTHENLADO THENISTIDO' END) AS TIPOOPERACION,--3
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS DATE) AS FECHA,--4
CAST(DATEADD(HOUR,-6,UA.ADDDATE) AS TIME) AS HORA,--5
UA.USERID AS USUARIO,--6
UA.EQUIPMENTID AS EQUIPO,--7
IT.FROMLOC AS UBICACIONRIGEN,--8
IT.TOLOC AS UBICACIONDESTINO,--9
IT.SKU as ARTICULO,--10
S.DESCR AS DESCRIPCION,--11
IT.UOMQTY AS CANTIDADCAJAS,--12
IT.QTY AS CANTIDADUNIDADES,
UA.STARTTIME AS INICIO,--13
UA.ENDTIME AS FIN--14
FROM WMWHSE51.USERACTIVITY AS UA
INNER JOIN WMWHSE51.ITRN AS IT
ON UA.ITRNKEY = IT.ITRNKEY
INNER JOIN WMWHSE51.SKU AS S
ON IT.SKU = S.SKU AND IT.storerkey = S.storerkey
