SELECT
PROPIETARIO,
PEDIDO,
count(ETIQUETA) AS CAN_ETIQUETA,
ARTICULO,
DESCRIPCION,
OLA,
ETIQUETA,
SUM(CANTIDADPREPARADA) AS CANTIDADPREPARADA,
SUM(Unidades) as Unidades,
(SELECT DISTINCT COUNT(W.ORDERKEY) from WMWHSE51.wavedetail AS W
where W.WAVEKEY = OLA) AS CANTIDAPEDIDO,
isnull((SELECT COUNT(pdd.ID) FROM WMWHSE51.PICKDETAIL pdd WHERE 
pdd.ORDERKEY = PEDIDO and pdd.id like 'P%'  AND pdd.sku = ARTICULO ),0) as PICKING,
isnull(( SELECT COUNT(pdd.ID) FROM WMWHSE51.PICKDETAIL pdd WHERE 
pdd.ORDERKEY = PEDIDO and pdd.id like 'R%' AND pdd.sku = ARTICULO ),0) as EXTRACCIONES
FROM (
SELECT
PD.STORERKEY AS PROPIETARIO,
PD.ID AS ETIQUETA,
PD.ORDERKEY AS PEDIDO,
PD.SKU as Articulo,
PD.qty as Unidades,
PD.QTY as candidadinidades,
(PD.QTY/ pa.CASECNT) AS CANTIDADPREPARADA,
s.descr as DESCRIPCION,
WA.WAVEKEY as OLA,
OD.CONSIGNEEKEY AS CO_TIENDA
FROM WMWHSE51.PICKDETAIL AS PD
LEFT JOIN WMWHSE51.ORDERS AS OD ON PD.ORDERKEY  = OD.ORDERKEY
LEFT JOIN WMWHSE51.sku    as S  on PD.sku = S.sku AND PD.STORERKEY = S.STORERKEY
LEFT JOIN WMWHSE51.pack  as pa  on s.packkey = pa.packkey
LEFT JOIN WMWHSE51.WAVEDETAIL as WA ON PD.ORDERKEY = WA.ORDERKEY
--WHERE WA.WAVEKEY like '%101%'
)T0
GROUP BY ARTICULO, PEDIDO, OLA , DESCRIPCION, PROPIETARIO,  ETIQUETA



select ORDERKEY, ADDWHO, ADDDATE from WMWHSE51.wavedetail
where WAVEKEY like '%524%'