SELECT
ETIQUETA
,PEDIDO
,O.CONSIGNEEKEY AS TIENDA
,ST.DESCRIPTION AS TIENDANOMBRE
,W.EDITWHO AS EXPEDICIONARIO
,CANAL
,CANTIDAD
FROM(
SELECT 
PD.ID AS ETIQUETA
,OD.ORDERKEY AS PEDIDO
,WD.WAVEKEY AS OLA
,PD.LOC AS CANAL
,PD.QTY AS CANTIDAD
FROM WMWHSE51.PICKDETAIL AS PD
LEFT JOIN WMWHSE51.ORDERDETAIL AS OD
ON PD.ORDERKEY = OD.ORDERKEY AND PD.QTY > 0
LEFT JOIN WMWHSE51.WAVEDETAIL AS WD
ON PD.ORDERKEY = WD.ORDERKEY
)T0
LEFT JOIN WMWHSE51.ORDERS AS O
ON T0.PEDIDO = O.ORDERKEY
LEFT JOIN WMWHSE51.STORER AS ST
ON O.CONSIGNEEKEY = ST.STORERKEY
LEFT JOIN WMWHSE51.WAVE AS W
ON T0.OLA = W.WAVEKEY
