SELECT 
MAX(TIENDA) AS TIENDA
,MAX(NOMBRETIENDA) AS NOMBRETIENDA
,OLA
,MAX(PEDIDO) AS PEDIDO
,MAX(CANAL) AS CANAL
,MAX(FECHALANZAMIENTO) AS FECHALANZAMIENTO
,SUM(BULTOSENVIADOS) AS BULTOSENVIADOS
,SUM(BULTOSPEDIDOS) AS BULTOSPEDIDOS
,SUM(BULTOSPREPARADOS) AS BULTOSPREPARADOS
,SUM(BULTOSPICK) AS BULTOSPICK
,SUM(ETIQUETAS) AS ETIQUETAS
,MAX(FECHAPREEXPEDICION) AS FECHAPREEXPEDICION
,MAX(USUARIO) AS USUARIO
FROM (
SELECT 
MAX(O.STATUS) AS ESTADO
,O.CONSIGNEEKEY AS TIENDA
,ST.DESCRIPTION AS NOMBRETIENDA
,MAX(WD.WAVEKEY) AS OLA
,O.ORDERKEY AS PEDIDO
,PD.LOC AS CANAL
,MAX(W.ADDDATE) AS FECHALANZAMIENTO
,OD.SKU AS CODIGO
,SUM(OD.SHIPPEDQTY) AS BULTOSENVIADOS
,SUM(OD.ORIGINALQTY) AS BULTOSPEDIDOS
,SUM(OD.PROCESSEDQTY) AS BULTOSPREPARADOS
,SUM(OD.QTYPICKED) AS BULTOSPICK
,COUNT(PD.ID) AS ETIQUETAS
,MAX(TL.ADDDATE) AS FECHAPREEXPEDICION
,MAX(w.EDITWHO) AS USUARIO
FROM WMWHSE51.ORDERDETAIL AS OD
LEFT JOIN WMWHSE51.WAVEDETAIL AS WD ON OD.ORDERKEY = WD.ORDERKEY
LEFT JOIN WMWHSE51.WAVE AS W ON WD.WAVEKEY = W.WAVEKEY
LEFT JOIN WMWHSE51.ORDERS AS O ON OD.ORDERKEY = O.ORDERKEY
LEFT JOIN WMWHSE51.STORER AS ST ON O.CONSIGNEEKEY = ST.STORERKEY
LEFT JOIN WMWHSE51.PACK AS PA ON OD.PACKKEY = PA.PACKKEY 
LEFT JOIN WMWHSE51.TRANSMITLOG AS TL ON WD.WAVEKEY = TL.KEY1 
LEFT JOIN WMWHSE51.PICKDETAIL AS PD ON OD.ORDERKEY = PD.ORDERKEY 
where O.STATUS IN ('55','95') 
--and wd.wavekey like '0000000166'
GROUP BY OD.SKU, O.CONSIGNEEKEY, ST.DESCRIPTION, PD.LOC, O.ORDERKEY
)T0
GROUP BY OLA