SELECT
MAX(OD.C_COMPANY) as Tienda,
MAX(cast(DATEADD(hour,-6,OD.ADDDATE) as date)) as FechaCreacionPedido,
--PD.WAVEKEY AS OLA ,
isnull(MAX(alt.ALTSKU), '--') as EAN13,
SUM(OT.ORIGINALQTY/ nullif(Pk.CASECNT,0))  as PEDIDAS,

(
CASE
WHEN MAX(OT.status) <> 95 THEN
SUM(ABS(OT.QTYPICKED)/ nullif(Pk.CASECNT,0))
ELSE
SUM(ABS(OT.PROCESSEDQTY)/nullif(Pk.CASECNT,0))
END
) as SERVIDAS,
(
(
CASE
WHEN MAX(OT.status) <> 95 THEN
SUM(ABS(OT.QTYPICKED)/ nullif(Pk.CASECNT,0))
ELSE
SUM(ABS(OT.PROCESSEDQTY)/nullif(Pk.CASECNT,0))
END
)
    /
SUM(OT.ORIGINALQTY/ nullif(Pk.CASECNT,0))
) as CUMPLIMIENTO,
'CAJA' as MEDIDA,
MAX(OT.STORERKEY) as PROPIETARIO,
OT.sku as Articulo,
MAX(SK.descr) as Descripcion,
OD.ORDERKEY,
ISNULL((
SELECT
SUM(LD.qty / nullif(p.CASECNT,0 )) 
FROM WMWHSE51.LOTXLOCXID LD
LEFT JOIN WMWHSE51.SKU s  ON LD.sku = s.sku
LEFT JOIN WMWHSE51.PACK p On s.PACKKEY  = p.PACKKEY
WHERE LD.status not like '%HOLD%'   and LD.qty > 0
and LD.storerkey like '%1770142%' and LD.sku =  OT.sku
),0) as 'STOCK BLOQUEADO',
(
SELECT
TOP 1
LI.LOC
FROM WMWHSE51.LOTXLOCXID  LI
LEFT JOIN  WMWHSE51.LOC   L on LI.loc = LI.loc
WHERE LI.status not like '%HOLD%'   and LI.qty > 0
and LI.storerkey like '%1770142%' and LI.sku =  OT.sku
AND L.loclevel = 1
) as 'UBICACIONES'
FROM     WMWHSE51.ORDERS OD
LEFT JOIN WMWHSE51.ORDERDETAIL OT ON OD.ORDERKEY = OT.ORDERKEY
-- LEFT JOIN WMWHSE51.PICKDETAIL  PD ON OD.ORDERKEY = PD.ORDERKEY AND OT.sku = PD.sku
LEFT JOIN WMWHSE51.SKU SK ON   OT.SKU = SK.SKU AND OT.STORERKEY = SK.STORERKEY
LEFT JOIN WMWHSE51.PACK PK ON SK.PACKKEY = PK.PACKKEY
LEFT JOIN WMWHSE51.ALTSKU alt ON   OT.sku = alt.sku and alt.TYPE = 'EAN13'
where ot.STORERKEY LIKE '%1770142%' --AND OT.ORDERKEY like '%0000000192%' --
GROUP BY OD.ORDERKEY, OT.sku, pk.CASECNT





