SELECT
CODIGO
,ORDEN
,OLA
,QTYSOLICITADA
,DIASPRECADUCIDAD
,DIAS
,QTYNOPREPARADA
,CANTIDADPREPARADA
,DISPONIBLE
,(CASE 
WHEN DISPONIBLE = 0 THEN 'NO HAY STOCK DISPONIBLE'
WHEN QTYSOLICITADA > DISPONIBLE THEN 'CANTIDAD INSUFICIENTE'
WHEN DIASPRECADUCIDAD > DIAS THEN 'PRODUCTO PRECADUCADO'
WHEN DIAS < 0 THEN 'PRODUCTO CADUCADO'
ELSE 'VALIDAR CON EQUIPO DE IMPLEMENTACION'
END) AS MOTIVO
--,UBICACION
FROM(SELECT
OD.ORDERLINENUMBER AS LINEAOD,
OD.SKU AS CODIGO,
--OD.PACKKEY AS PAQUETA,
SUM(OD.OPENQTY) AS QTYSOLICITADA,  
OD.ORDERKEY AS ORDEN,
OD.SHELFLIFE AS DIASPRECADUCIDAD,
VW.WAVEKEY AS OLA,
SUM(WA.OPENQTY) AS QTYNOPREPARADA, 
SUM(WA.SHIPPEDQTY) AS CANTIDADPREPARADA, 
WA.ORDERLINENUMBER AS LINEAVW, 
--WA.STATUS AS ESTADO,
RIGHT(LT.LOT,5) AS LOTE,
ISNULL(DATEDIFF(DAY,getdate(),LT.LOTTABLE05), 0) AS DIAS,
ISNULL(SUM(LLT.QTY-LLT.QTYPICKED),0) AS DISPONIBLE
--,LLT.LOC AS UBICACION
FROM WMWHSE51.ORDERDETAIL AS OD
LEFT JOIN WMWHSE51.vWaveOrders AS VW
ON OD.ORDERKEY = VW.ORDERKEY 
LEFT JOIN WMWHSE51.vOrderDetailStatusCode AS WA
ON OD.ORDERKEY = WA.ORDERKEY 
LEFT JOIN WMWHSE51.LOTXLOCXID AS LLT
ON OD.SKU = LLT.SKU
LEFT JOIN WMWHSE51.LOTATTRIBUTE AS LT
ON LT.SKU = LLT.SKU AND LT.LOT = LLT.LOT
WHERE WA.OPENQTY > 0 AND OD.ORDERLINENUMBER = WA.ORDERLINENUMBER 
--AND OD.STATUS NOT LIKE '75' 
--AND VW.WAVEKEY LIKE '%607'
GROUP BY OD.ORDERLINENUMBER, OD.SKU, OD.ORDERKEY, OD.SHELFLIFE,
VW.WAVEKEY, OD.ORIGINALQTY, WA.ORDERLINENUMBER, LT.LOT, LT.LOTTABLE05--,LLT.LOC
)T0