/*
ARTICULO
DESCRIPCION
IDOPERACION
PRIORIDAD
OPERACION
ETIQUETA
PEDIDAS
SERVIDAS
UBICACION
*/
SELECT TA.SKU AS ARTICULO,
       SK.DESCR AS DESCRIPCION,
       TA.PRIORITY AS PRIORIDAD,
       CO.DESCRIPTION AS OPERACION,
       TA.FROMID AS ETIQUETA,
       TA.FROMLOC AS UBICACIONORIGEN,
       TA.TOLOC AS UBICACIONDESTINO,
       TA.WAVEKEY AS OLA,
       TA.ORDERKEY AS PEDIDO,
       TA.STATUS AS ESTADO,
       CO2.DESCRIPTION AS ESTADODESCRIPCION,
       OD.OPENQTY AS CANTIDADSOLICITADA,
       TA.QTY AS CANTIDAD,
       TA.TASKTYPE AS TIPOTAREA,
       TA.taskdetailkey as IDOperacion
FROM wmwhse51.TASKDETAIL AS TA
LEFT JOIN wmwhse51.SKU AS SK ON TA.SKU = SK.SKU
LEFT JOIN wmwhse51.CODELKUP AS CO ON TA.TASKTYPE = CO.CODE
AND CO.LISTNAME LIKE '%TASKTYPE%'
LEFT JOIN wmwhse51.CODELKUP AS CO2 ON TA.STATUS = CO2.CODE
AND CO2.LISTNAME LIKE '%ACTVSTAT%'
LEFT JOIN wmwhse51.ORDERDETAIL AS OD ON TA.ORDERKEY = OD.ORDERKEY
AND TA.SKU = OD.SKU
AND OD.OPENQTY > 0
WHERE TA.TASKTYPE LIKE 'RP'
AND ta.status <> '9'