SELECT
OLA
,PEDIDO
,CODIGO
,(CANTIDADPEDIDA/PA.CASECNT) AS CANTIDADPEDIDA
,(CANTIDADPREPARADA/PA.CASECNT) AS CANTIDADPREPARADA
,DESCRIPCION
,FACTOR
FROM(
SELECT 
WD.WAVEKEY AS OLA
,OD.ORDERKEY AS PEDIDO
,OD.SKU AS CODIGO
,(CASE 
WHEN OD.status <> 95 THEN SUM(OD.QTYPICKED) 
ELSE  SUM(OD.SHIPPEDQTY) END) AS CANTIDADPREPARADA
,SUM(OD.ORIGINALQTY) AS CANTIDADPEDIDA
,MAX(SK.DESCR) AS DESCRIPCION
,MAX(OD.PACKKEY) AS FACTOR
FROM  WMWHSE51.ORDERDETAIL AS OD
LEFT JOIN WMWHSE51.WAVEDETAIL as WD
ON OD.ORDERKEY = WD.ORDERKEY 
LEFT JOIN WMWHSE51.SKU AS SK
ON OD.SKU = SK.SKU AND OD.STORERKEY = SK.STORERKEY
GROUP BY OD.ORDERKEY, WD.WAVEKEY,OD.SKU, OD.STATUS
)T0 
LEFT JOIN WMWHSE51.PACK AS PA
ON T0.FACTOR = PA.PACKKEY 
--WHERE OLA LIKE '0000000203'
