SELECT DISTINCT 
PD1.ORDERKEY AS PEDIDO,
max(PD1.ID) AS ETIQUETA,
max(PD1.ADDWHO) AS USUARIO,
max(PD1.SKU) AS CODIGO,
max(SK.DESCR) AS DESCRIPCION,
max(CAST(WD.ADDDATE AS DATE)) AS FECHA,
WD.WAVEKEY AS OLA,
max(O.CONSIGNEEKEY) AS TIENDA
FROM WMWHSE51.PICKDETAIL AS PD1
LEFT JOIN WMWHSE51.SKU AS SK
ON PD1.SKU = SK.SKU AND PD1.PACKKEY = SK.PACKKEY
LEFT JOIN WMWHSE51.WAVEDETAIL AS WD
ON PD1.ORDERKEY = WD.ORDERKEY
LEFT JOIN WMWHSE51.ORDERS AS O
ON PD1.ORDERKEY = O.ORDERKEY
WHERE PD1.ID IN (SELECT ETIQUETA FROM(SELECT 
ETIQUETA,
MAX(PEDIDO) AS PEDIDO
FROM(SELECT DISTINCT ISNULL(PD.ID,'--') AS ETIQUETA, PD.ORDERKEY AS PEDIDO
FROM WMWHSE51.PICKDETAIL AS PD)T0
GROUP BY ETIQUETA
HAVING COUNT(PEDIDO) > 1)T1)
GROUP BY PD1.ORDERKEY, WD.WAVEKEY
--HAVING COUNT(WD.WAVEKEY) <> 1
--ORDER BY max(PD1.ID)