SELECT *
FROM(
SELECT
LLI.SKU AS CODIGO,
LLI.LOC AS UBICACION,
LLI.ID AS ETIQUETA,
LLI.LOT AS LOTEINTERNO,
LLI.QTY AS CANTIDADUNIDAD,
(LLI.QTY/PA.CASECNT) AS CANTIDADCAJAS,
(IIF(LLI.STATUS LIKE 'HOLD','BLOQUEADO','APTO')) AS ESTADO,
LLI.STORERKEY AS PROPIETARIO,
LLI.RECEIVINGNUM AS NUMERORECEPCION,
VLL.LOTTABLE05 AS FECHAVENCIMIENTO,
VLL.LOTTABLE06 AS LOTE,
DATEDIFF(DAY,GETDATE(),VLL.LOTTABLE05) AS DIASVENCIMIENTO,
(CASE WHEN DATEDIFF(DAY,GETDATE(),VLL.LOTTABLE05) < 0 THEN 'CADUCADO'
WHEN DATEDIFF(DAY,GETDATE(),VLL.LOTTABLE05) >= 0 AND 
DATEDIFF(DAY,GETDATE(),VLL.LOTTABLE05) < SK.shelflife THEN 'PRECADUCADO'
ELSE 'APTO' END) as CADUCIDAD,
-- DATEDIFF(DAY,GETDATE(),VLL.LOTTABLE05) >= SK.shelflife THEN 
VLL.LOTTABLE09 AS ASNRECEPCION,
SK.DESCR AS DESCRIPCION,
RD.RECEIPTKEY AS ASN
FROM WMWHSE52.LOTXLOCXID AS LLI
LEFT JOIN WMWHSE52.vITLotxLocxId_Lottables AS VLL
ON LLI.LOC = VLL.LOC AND LLI.ID = VLL.ID AND LLI.LOT = VLL.LOT
LEFT JOIN WMWHSE52.SKU AS SK
ON LLI.SKU = SK.SKU AND LLI.STORERKEY = SK.STORERKEY
LEFT JOIN WMWHSE52.RECEIPTDETAIL AS RD
ON LLI.LOT = RD.TOLOT AND SK.SKU = RD.SKU AND LLI.ID = RD.TOID
LEFT JOIN WMWHSE52.PACK AS PA 
ON SK.PACKKEY = PA.PACKKEY)T0
WHERE CADUCIDAD IN ('CADUCADO','PRECADUCADO') AND ESTADO NOT LIKE ('BLOQUEADO')



WHERE LLI.STATUS <> 'HOLD' AND DATEDIFF(DAY,GETDATE(),VLL.LOTTABLE05) < SK.shelflife OR DATEDIFF(DAY,GETDATE(),VLL.LOTTABLE05) < 0
AND LLI.STORERKEY LIKE '%QUALA_SPS%' AND LLI.LOT LIKE '%147'