/*esto es un comentario*/
SELECT DISTINCT
(LT.QTY/PA.CASECNT) AS 'CANTIDADCAJAS',
LT.LOC,
LT.ID,
LT.SKU,
SK.DESCR,
LT.LOTTABLE05,
SK.SHELFLIFE AS 'DIAS SALIDA',
DATEDIFF(DAY,getdate(),LT.LOTTABLE05)as 'DIAS PARA VENCIMIENTO',
(CASE 
    WHEN (LT.LOTTABLE05>DATEADD(DAY,SK.SHELFLIFE,GETDATE()))
    THEN 'FECHA CORRECTA'ELSE 'PRECADUCADO'END) AS 'ALERTA DE VENCIMIENTO',
AL.ALTSKU AS EAN13,RC.DATERECEIVED,
RC.EXTERNRECEIPTKEY as OrdenCompra,
RC.DATERECEIVED as FechadeRecepción 
FROM WMWHSE51.vITLotxLocxId_Lottables AS LT 
LEFT JOIN WMWHSE51.SKU AS SK 
ON LT.SKU = SK.SKU LEFT JOIN WMWHSE51.PACK AS PA 
ON SK.PACKKEY = PA.PACKKEY 
LEFT JOIN WMWHSE51.ALTSKU AS AL 
ON SK.SKU = AL.SKU AND AL.TYPE = 'EAN13'
LEFT JOIN WMWHSE51.RECEIPTDETAIL AS RC 
ON LT.ID = RC.TOID AND SK.SKU = RC.SKU 