SELECT
LLI.STORERKEY,
LLI.SKU,
LLI.ADDWHO  AS 'USUARIO',
LLI.LOC AS 'UBICACION',
(LLI.QTY/ p.CASECNT ) AS 'CANTIDADCAJAS',
LLI.ID 'ETIQUETA',
LLI.LOT AS 'LOTEINTERNO',
isnull(LT.LOTTABLE05,'') AS 'FECHAVENCIMIENTO',
isnull(LT.LOTTABLE06,'') AS 'LOTEDEREPROPIETARIO',
DATEDIFF(DAY,getdate(),LT.LOTTABLE05) as 'DIAS PARA VENCIMIENTO',

-- IIF(LLI.STATUS like '%HOLD%', 'Bloqueado', 
-- (CASE
-- WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) > s.SHELFLIFEONRECEIVING THEN 'APTO'
-- WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) between s.SHELFLIFE and s.SHELFLIFEONRECEIVING THEN 'Precaducado'
-- WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) <= s.SHELFLIFE THEN 'Caducado'
-- ELSE ''
-- END  )) as ESTADO,

IIF(LLI.STATUS like '%HOLD%', 'Bloqueado', 
(CASE
WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) > s.SHELFLIFE THEN 'APTO'
WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) between 0 and s.SHELFLIFE THEN 'Precaducado'
WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) < 0 THEN 'Caducado'
ELSE ''
END  )) as ESTADO,


-- IIF(LLI.STATUS like '%HOLD%' AND ( DATEDIFF(DAY,getdate(),LT.LOTTABLE05) > s.SHELFLIFEONRECEIVING), (SELECT TOP 1 IHC.DESCRIPTION
-- FROM WMWHSE52.INVENTORYHOLDCODE AS IHC
-- INNER JOIN WMWHSE52.INVENTORYHOLD AS H
-- ON IHC.CODE = H.STATUS
-- WHERE H.ID = LLI.ID
-- AND H.adddate = (
-- SELECT MAX(adddate)
-- FROM WMWHSE52.INVENTORYHOLD AS H
-- WHERE H.ID = LLI.ID
-- )),
-- (CASE
-- WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) between s.SHELFLIFE and s.SHELFLIFEONRECEIVING THEN 'Precaducado'
-- WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) <= s.SHELFLIFE THEN 'Caducado'
-- ELSE ''
-- END  )
-- ) as MOTIVO,

IIF(LLI.STATUS like '%HOLD%' AND ( DATEDIFF(DAY,getdate(),LT.LOTTABLE05) > s.SHELFLIFE), 
(SELECT TOP 1 IHC.DESCRIPTION
FROM WMWHSE52.INVENTORYHOLDCODE AS IHC
INNER JOIN WMWHSE52.INVENTORYHOLD AS H
ON IHC.CODE = H.STATUS
WHERE H.ID = LLI.ID
AND H.adddate = (
SELECT MAX(adddate)
FROM WMWHSE52.INVENTORYHOLD AS H
WHERE H.ID = LLI.ID
)),
(CASE
WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) > s.SHELFLIFE THEN ''
WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) between 0 and s.SHELFLIFE THEN 'Precaducado'
WHEN DATEDIFF(DAY,getdate(),LT.LOTTABLE05) < 0 THEN 'Caducado'
ELSE ''
END  )
) as MOTIVO,

(s.DESCR)AS 'DESCRIPCIONARTICULO',
ISNULL((
select TOP 1 RD.RECEIPTKEY FROM WMWHSE52.RECEIPTDETAIL RD
where RD.TOID = LLI.ID and RD.sku = LLi.sku AND rd.toid <> '' AND rd.toid is not null
),'Carga Inicial') AS RECEIPTKEY,
(
select TOP 1 DATEADD(hour, -6 ,RD.DATERECEIVED)  FROM WMWHSE52.RECEIPTDETAIL RD
where RD.TOID = LLI.ID
) AS FECHARECEPCION,
LLI.ID
FROM WMWHSE52.LOTXLOCXID AS LLI
LEFT JOIN WMWHSE52.LOTATTRIBUTE AS LT ON LLI.LOT = LT.LOT
AND LLI.SKU = LT.SKU
LEFT JOIN WMWHSE52.LOC LO ON LLI.LOC = LO.LOC
LEFT JOIN WMWHSE52.sku s on LLI.sku = s.sku AND LLI.storerkey = S.storerkey
LEFT JOIN WMWHSE52.pack p on s.PACKKEY = p.PACKKEY
WHERE LLI.QTY > 0 AND LLI.loc not like '%MP50-1-1%';


SELECT count(distinct LT.sku), '*' FROM WMWHSE52.LOTXLOCXID LT 
WHERE LT.qty > 0