/*
ZONA
PASILLO
COLUMNA
NIVEL
COMPARTIMENTO
CODIGO
EAN13
DESCRIPCION
VENCIMIENTO
ETIQUETA
FACTORDESPACHO
UNIDADESCAJA
TOTALCAJAS
TOTALUNIDADES
*/

SELECT 
LO.PUTAWAYZONE AS ZONA
,LLI.LOC AS UBICACION
,LLI.SKU AS CODIGO
,AL.ALTSKU EAN13
,SK.DESCR AS DESCRIPCION
,LLI.ID AS ETIQUETA
,vLLI.LOTTABLE05 VENCIMIENTO
,(LLI.QTY/PA.CASECNT) AS TOTALCAJAS
,PA.CASECNT AS UNIDADESCAJA
,LLI.QTY AS TOTALUNIDADES
,RC.SUPPLIERNAME AS PROVEEDOR
,SK.RFDEFAULTUOM AS FACTORDESPACHO
FROM WMWHSE51.LOTXLOCXID AS LLI
LEFT JOIN WMWHSE51.LOC AS LO
ON LLI.LOC = LO.LOC
LEFT JOIN WMWHSE51.ALTSKU AS AL
ON LLI.SKU = AL.SKU AND AL.TYPE LIKE 'EAN13' AND LLI.STORERKEY = AL.STORERKEY
LEFT JOIN WMWHSE51.SKU AS SK
ON LLI.SKU = SK.SKU AND LLI.STORERKEY = SK.STORERKEY
LEFT JOIN WMWHSE51.vITLotxLocxId_Lottables AS vLLI
ON LLI.LOC = vLLI.LOC AND LLI.ID = vLLI.ID
LEFT JOIN WMWHSE51.PACK AS PA
ON SK.PACKKEY = PA.PACKKEY
LEFT JOIN WMWHSE51.RECEIPTDETAIL AS RD
ON LLI.SKU = RD.SKU AND LLI.ID = RD.TOID
LEFT JOIN WMWHSE51.RECEIPT AS RC
ON RD.RECEIPTKEY = RC.RECEIPTKEY
WHERE LLI.STORERKEY LIKE '1770142' AND LEN(LLI.ID)>2