/*
proveedorcodigo
prveedornombre
FECHAORDEN
ORDENCOMPRA
FECHACADUCIDAD
UNIDADES
SKUCODIGO
SKUDESCRIPCION
FECHAORDENRECIBIDA
ORDENCOMPRARECIBIDA
FECHACADUCIDADRECIBIDA
UNIDADESRECIBIDA
*/

SELECT DISTINCT
MAX(RD.SUPPLIERKEY) AS CODIGOPROVEEDOR
,MAX(RD.SUPPLIERNAME) AS NOMBREPROVEEDOR
,MAX(RC.ADDDATE) AS FECHAORDEN
,MAX(RD.EXTERNRECEIPTKEY) AS ORDENCOMPRA
,MAX(RD.LOTTABLE05) AS FECHACADUCIDAD
,SUM(RD.QTYRECEIVED) AS UNIDADES
,RD.SKU AS CODIGO
,MAX(SK.DESCR) AS DESCRIPCION
,MAX(RD.DATERECEIVED) AS FECHARECEPCION
,DATEDIFF(DAY,MAX(RD.DATERECEIVED),GETDATE())  DIASULTIMARECEPCION 

FROM WMWHSE51.RECEIPTDETAIL AS RD
LEFT JOIN WMWHSE51.RECEIPT AS RC
ON RD.RECEIPTKEY = RC.RECEIPTKEY
LEFT JOIN WMWHSE51.SKU AS SK
ON RD.SKU = SK.SKU
WHERE RD.EXTERNRECEIPTKEY NOT like('INI%')
GROUP BY RD.SKU


/**/
SELECT * FROM WMWHSE51.RECEIPTDETAIL WHERE EXTERNRECEIPTKEY LIKE '000000003004214370'
