/*validacion de capos tablas skuxloc*/
SELECT
SKU,
LOCATIONTYPE,
LOC
FROM WMWHSE51.SKUXLO
WHERE SKU LIKE '1000007'

/*validacion de capos loc*/
SELECT
LOCLEVEL,
LOCATIONTYPE,
LOCATIONCATEGORY,
LOC
FROM WMWHSE51.LOC
WHERE LOC LIKE '6-41-1-3'

/*
sector
codigo
ean13
descripcion
pasillo
columna
nivel
compartimento
*/

SELECT
ZONA
,CODIGO
,EAN13
,DESCRIPCION
,NIVEL
,TIPOUBICACION
,LOCATIONCATEGORY
,STRING_AGG( UBICACION,' | ') AS UBICACIONES
,COUNT(UBICACION) AS CANTIDAD
FROM(
SELECT
SK.PUTAWAYZONE AS ZONA,
SK.SKU AS CODIGO,
AL.ALTSKU AS EAN13,
SK.DESCR AS DESCRIPCION,
SKL.LOC AS UBICACION,
LO.LOCLEVEL AS NIVEL,
LO.LOCATIONTYPE AS TIPOUBICACION,
LO.LOCATIONCATEGORY AS LOCATIONCATEGORY
FROM WMWHSE51.SKU AS SK
LEFT JOIN WMWHSE51.ALTSKU AS  AL
ON SK.SKU = AL.SKU AND AL.TYPE LIKE 'EAN13' AND SK.STORERKEY = AL.STORERKEY
LEFT JOIN WMWHSE51.SKUXLOC AS SKL
ON SK.SKU = SKL.SKU
LEFT JOIN WMWHSE51.LOC AS LO
ON SKL.LOC = LO.LOC 
WHERE 
LO.LOCLEVEL = 1 AND
 SK.STORERKEY LIKE '1770142'
)T0
GROUP BY
ZONA
,CODIGO
,EAN13
,DESCRIPCION
,NIVEL
,TIPOUBICACION
,LOCATIONCATEGORY
HAVING COUNT(UBICACION) > 1  
