/*
ARTICULO
DESCRIPCION
ROTACIONPICKING
ROTACIONRESERVA
CONTAMINACION
LOCALIZACION
REFRIGERACION
IMFLAMABLE
CAJAS
FACTOR EMPAQUE
CALIDAD
PALETIZADO
*/

SELECT
SK.SKU AS CODIGO,
SK.DESCR AS DESCRIPCION,
ISNULL((SELECT SUM(LLT1.QTY) AS CANTIDAD--, ''
FROM WMWHSE51.LOTXLOCXID AS LLT1
WHERE LLT1.SKU like SK.SKU
)/PA.CASECNT,0) AS CANTIDAD,
SK.PUTAWAYZONE AS ZONA,
PA.CASECNT AS FACTOREMPAQUE,
CONCAT(floor(PA.PALLETTI),' X ',floor(PA.PALLETHI)) AS PALETIZADO
FROM WMWHSE51.SKU AS SK
LEFT JOIN WMWHSE51.SKUXLOC AS SKL
ON SK.SKU = SKL.SKU
LEFT JOIN WMWHSE51.LOC AS LO
ON SKL.LOC = LO.LOC
LEFT JOIN WMWHSE51.PACK AS PA
ON SK.PACKKEY = PA.PACKKEY
WHERE SK.SKU 
--like '1018790'
NOT IN (SELECT 
--SK1.LOC, LO1.LOCLEVEL,
 SK1.SKU
FROM WMWHSE51.SKUXLOC AS SK1 
INNER JOIN WMWHSE51.LOC AS LO1
ON SK1.LOC = LO1.LOC AND LO1.LOCLEVEL <> 1)
AND SK.STORERKEY LIKE '1770142' AND PA.CASECNT > 0

/*VALIDACION DE SUMA DE STOCK DISPONIBLE*/

SELECT SUM(LLT1.QTY) AS CANTIDAD--, ''
FROM WMWHSE51.LOTXLOCXID AS LLT1
WHERE LLT1.SKU like '1018790'

