/*
ARTICULO
DESCRIPCION
ACTIVO -*
DESCRIPCION FR -*
ALTO
ANCHO
LARGO
PESO
(VALIDADO SERVIDOR - VALIDADO CLIENTE ) VALIDACION MANUAL
(ROTACION PICK - ROTACION RESERVA) ROTACION
CONTAMINANTE -
LOCALIZACION -
REFRIGERACION -
INFLAMABLE -
EAN UNIDAD
DUM CAJA
CODIGO FAMILIA
DESCRIPCION FAMILIA
CODIGO PROVEEDOR
DESCRIPCION PROVEEDOR
UBICACION
STOCK
DIAS CADUCIDAD
DIAS PRE CADUCADO
FACTOR EMPAQUE
TIPO CONTENEDOR
*/

SELECT
ARTICULO
,DESCRIPCION
,UNIDADALTO
,UNIDADANCHO
,UNIDADLARGO
,UNIDADPESO
,VALIDACIONPENDIENTE
,EAN13
,DUM14
,FAMILIA
,FAMILIADESCRIPCION
,PROVEEDORCODIGO
,PROVEEDORDESCRIPCION
,UBICACION
,DIASPRECADUCIDAD
,DIASCADUCIDAD
,FACTOREMPAQUE
,TIPOCONTENEDOR
,ROTACION
,CANTIDAD
FROM(
    SELECT 
SK.SKU AS ARTICULO
,SK.DESCR AS DESCRIPCION
,PA.HEIGHTUOM3  AS UNIDADALTO
,PA.WIDTHUOM3  AS UNIDADANCHO
,PA.LENGTHUOM3 AS UNIDADLARGO
,PA.WEIGHTUOM3 AS UNIDADPESO
,IIF(SK.MANUALSETUPREQUIRED=0,'ACTIVO','PENDIENTE VALIDACION') AS VALIDACIONPENDIENTE
,AL1.ALTSKU AS EAN13
,AL2.ALTSKU AS DUM14
,SK.STOCKCATEGORY AS FAMILIA
,CO.DESCRIPTION AS FAMILIADESCRIPCION
,'' PROVEEDORCODIGO
,'' PROVEEDORDESCRIPCION
,SKL.LOC AS UBICACION
,SK.SHELFLIFEONRECEIVING AS DIASPRECADUCIDAD
,SK.SHELFLIFE AS DIASCADUCIDAD
,PA.CASECNT AS FACTOREMPAQUE
,IIF (PA.PACKUOM4 IS NOT NULL, 'PALLET',
IIF (PA.CASECNT IS NOT NULL, 'CAJA',
IIF (PA.PACKUOM1 IS NOT NULL, 'UNIDAD',''
))) AS TIPOCONTENEDOR
,(SELECT CO1.DESCRIPTION FROM WMWHSE51.CODELKUP AS CO1
WHERE CO1.CODE = SK.DEFAULTROTATION AND CO1.LISTNAME LIKE 'ROTATION') AS ROTACION
,(SELECT SUM(LTT.QTY)
FROM WMWHSE51.LOTXLOCXID AS LTT
WHERE LTT.SKU = SK.SKU AND LTT.LOC = SKL.LOC) AS CANTIDAD

FROM WMWHSE51.SKU AS SK
LEFT JOIN WMWHSE51.PACK AS PA
ON SK.PACKKEY = PA.PACKKEY
LEFT JOIN WMWHSE51.ALTSKU AS AL1
ON SK.SKU = AL1.SKU AND AL1.TYPE LIKE 'EAN13'
LEFT JOIN WMWHSE51.ALTSKU AS AL2
ON SK.SKU = AL1.SKU AND AL2.TYPE LIKE 'DUM14'
LEFT JOIN WMWHSE51.CODELKUP AS CO
ON SK.STOCKCATEGORY = CO.CODE
LEFT JOIN WMWHSE51.SKUXLOC AS SKL
ON SK.SKU = SKL.SKU
WHERE SK.STORERKEY LIKE '1770142'
)T0

/*
se debe validar calculo de stock en pase a productivo
*/

/*
CODE-DESCRIPCIOM-LISTNAME
1 -FIFO - First In, First Out -ROTATION
*/

